spring:
  ai:
    ollama:
      init:
        pull-model-strategy: always
        timeout: 60s
        max-retries: 1
      base-url: http://localhost:11434/
      model: llama2
      chat.options:
        model: llama3.2

      embedding:
        model: llama3.2